name: project_5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bottom_navbar_with_indicator: ^0.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
