name: project_5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_splash_screen: ^3.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.1.10
  flutter_date_range_picker: ^0.0.14
  flutter_date_pickers: ^0.4.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
